clear;
x = -2 : 0.2 : 10;
A = gauss(x, [2, 2]);
B = gauss(x, [3, 5]);
iloczyn = tnorma(A, B);
suma = snorma(A, B);
subplot(3, 1, 1);
plot(x, A, x, B);
grid;
subplot(3, 1, 2);
plot(x, suma);
grid;
subplot(3, 1, 3);
plot(x, iloczyn);
grid;
axis([min(x) max(x) 0 1]);
subplot(3, 1, 1);
title("SUMA A i B");
subplot(3, 1, 2);
title("Suma A i B");
subplot(3, 1, 3);
title("Iloczyn A i B");